{% set name = "seqeval" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63209166fd74b11e88f1fa0132614ce852c6e83f678de76f7a53672c2d16c8d2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - keras >=2.2.4
    - numpy
    - python

test:
  imports:
    - seqeval
    - seqeval.metrics

about:
  home: https://github.com/chakki-works/seqeval
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Testing framework for sequence labeling
  doc_url: https://pypi.org/project/seqeval/
  dev_url: https://github.com/chakki-works/seqeval

extra:
  recipe-maintainers:
    - oblute
    - benhuff
