{% set name = "seqeval" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f28e97c3ab96d6fcd32b648f6438ff2e09cfba87f05939da9b3970713ec56e6f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
    - setuptools
    - wheel
  run:
    - numpy >=1.14.0
    - python
    - scikit-learn >=0.21.3

test:
  imports:
    - seqeval
    - seqeval.metrics
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/chakki-works/seqeval
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for sequence labeling evaluation(named-entity recognition, pos tagging, etc...)
  description: seqeval is a Python framework for sequence labeling evaluation. seqeval can evaluate the performance of chunking tasks such as named-entity recognition, part-of-speech tagging, semantic role labeling and so on.
  doc_url: https://pypi.org/project/seqeval/
  dev_url: https://github.com/chakki-works/seqeval

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
